# Generated by Django 5.2.5 on 2025-11-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent")},
        ),
    ]
