# Generated by Django 5.2.5 on 2025-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0002_alter_category_name_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
