# Generated by Django 5.2.5 on 2025-11-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0005_remove_customer_appeal_message_customer_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="is_valid",
            new_name="is_active",
        ),
    ]
