# Generated by Django 5.2.7 on 2025-11-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "storefront",
            "0007_remove_customer_created_at_remove_customer_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for account deactivation (shown to user)",
                null=True,
            ),
        ),
    ]
