# Generated by Django 5.2.7 on 2025-11-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
