# Generated by Django 5.2.5 on 2025-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_customer_is_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="appeal_message",
            field=models.TextField(blank=True),
        ),
    ]
