# Generated by Django 5.2.8 on 2025-11-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0006_rename_is_valid_customer_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
    ]
