# Generated by Django 5.2.5 on 2025-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0009_appeal_appealdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="can_appeal",
            field=models.BooleanField(
                default=True,
                help_text="Whether this customer can submit appeals (set to False after appeal denial)",
            ),
        ),
    ]
