# Generated by Django 5.2.5 on 2025-11-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_customer_preferred_category"),
        ("storefront", "0010_customer_can_appeal"),
    ]

    operations = []
