# Generated by Django 5.2.5 on 2025-11-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0011_merge_20251113_0946"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="can_appeal",
        ),
    ]
